var fb = self.fb || {};
fb.fbOptions = {
global: {
	showMagCursor:true,
	pageScroll:false,
	shadowType:'none',
	shadowSize:0,
	outerBorder:0,
	innerBorder:0,
	boxCornerRadius:0,
	enableImageResize:false,
	enableDragMove:false,
	titleAsCaption:false,
	fetchVideoInfo:false,
	padding:0,
	minBoxWidth:300,
	maxWidth:1680,
	maxHeight:1680,
	overlayOpacity:1.0,
	resizeTime:0.7,
	transitionTime:0.6,
	animationTime:0.2,
	boxColor:'#eeeeee',
	textColor:'#111111',
	strongTextColor:'#111111',
	overlayColor:'#eeeeee',
	outerBorderColor:'#111111',
	captionPos:'bc',
	showItemNumber:false,
	controlsPos:'br',
	navType:'overlay',
	navOverlayWidth:45,
	autoFitSpace:15,
	doSlideshow:true,
	slideInterval:8,
	startPaused:true,
	afterSlideshow:'exit',
	autoPlayVideo:false,
	addVideoThumb:false,
	language:'zz'
},
mobile: {
	padding:0,
	minBoxWidth:140,
	showItemNumber:false,
	strictCentering:false,
	imageTransition:'slide',
	preloadLimit:1,
	autoFitSpace:5,
	enableImageResize:true
}
};
fb.data.strings = ["","","","","","","","Image %1 of %2","","","","","","","","",""];